version: "3.1"

services:
  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin1
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin1
      MYSQL_PASSWORD: admin1
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8851:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin1
    restart: always

  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - "8850:8000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=admin1
      - DB_DATABASE=laravel
    volumes:
      - "./my-project:/app"
    depends_on:
      - mysql

volumes:
  mysql_data:
