version: "3.1"

services:
  web:
    image: php:8.1-apache
    container_name: php_apache
    restart: always
    volumes:
      - /home/tes:/var/www/html
    ports:
      - "8850:80"
    depends_on:
      - mysql
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: notes
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8851:80
    environment:
      PMA_HOST: mysql

volumes:
  mysql_data:
