version: "3.8"
services:
  backend:
    image: node:20.11.0
    working_dir: /x
    volumes:
      - ./server:/x
    ports:
      - "8850:3000"
    command: sh -c "npm install && node app.js"

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  frontend:
    image: node:20.11.0
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8851:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  mongodata:
